language: csharp
solution: ./SimpleConsoleApp/SimpleConsoleApp.sln 
install:
  - nuget restore ./SimpleConsoleApp/SimpleConsoleApp.sln 
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ./SimpleConsoleApp/SimpleConsoleApp.sln 
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SimpleConsoleAppTests/bin/Debug/SimpleConsoleAppTests.dll

